### ISSUE TITLE
Post-update prediction

### ISSUE THREAD

**Issue by jtec** [andreabelles/Time-Synch#7]
It looks like in

https://github.com/andreabelles/Time-Synch/blob/0e9f025afd9d9a03953aae1ef78ba5003b9919a5/Estimation_Methods/skogEKF.m#L41-L44

There is a final prediction/propagation from GNSS observation (past) to the present. Is this done in the Skog EKF, or is their filter permanently running in the past?

**Comment by andreabelles** [comment]
We think their filter works permanently in the past, however, we discussed in previous meetings that it would not be complicated to propagate the integrated solution to the present. We can implement it and then compare both performances.

**Comment by jtec** [comment]
Ok, great! So that's one additional feature of your filter then that provides truely real-time estimates!
